server:
  port: 3000

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/airesume
#    username: postgres
#    password: postgres
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

jwt:
  secret: my-super-secret-key-which-is-at-least-32-characters
  expiration-ms: 86400000

rate-limit:
  capacity: 20
  duration: PT24H

spring:
  datasource:
    url: jdbc:h2:mem:airesume
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
